app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'
urlpatterns = [
    path('', views.index, name= 'home'),
    path('contact/', views.contact, name= 'contact'),
    path('math/', views.math, name= 'math'),
    path('table/', views.table, name= 'table'),
    path('reg/', views.reg, name= 'reg'),
]

pro2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
]

app1/models.py
from django.db import models

class members(models.Model):
    name = models.CharField(max_length=20)
    lastName = models.CharField(max_length=20)
    father = models.CharField(max_length=20)
    address = models.CharField(max_length=200)

app1/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render, HttpResponse
from app1.models import members
tasks = ['foo', 'bar', 'teo']


class newTaskForm(forms.Form):
    tas = forms.CharField(label='New Task :', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    name = forms.CharField(label='Name :', widget=forms.TextInput(
        attrs={'class': 'form-control'}))


    # name = forms.CharField(label='name :')
    # Address = forms.CharField(label='Address :')
m = {
    'num1': 0,
    'num2': 0,
    'result': 0,
}


def index(request):
    if request.method == "POST":
        fem = newTaskForm(request.POST)
        if fem.is_valid():
            task = fem.cleaned_data['tas']
            # n = fem.cleaned_data['name']
            # address = fem.cleaned_data['Address']
            tasks.append(task)
            return HttpResponseRedirect(reverse('app1:contact'))
        else:
            return render(request, 'app1/index.html', {
                'form': fem
            })
    return render(request, 'app1/index.html', {
        'form': newTaskForm()
    })


def contact(request):
    return render(request, 'app1/contact.html', {
        'task': tasks


    })
# v-------------------------- Math Formula --------------------------------------


class maths(forms.Form):
    num1 = forms.CharField(label='Number 1', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    op = forms.CharField(label='Operator', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    num2 = forms.CharField(label='Number 2', widget=forms.TextInput(
        attrs={'class': 'form-control'}))


def math(request):
    n1 = 0
    n2 = 0
    if request.method == "POST":
        fem = maths(request.POST)
        if fem.is_valid():
            # n1 = int(fem.cleaned_data['num1'])
            # n2 = int(fem.cleaned_data['num2'])
            m['num1'] = (fem.cleaned_data['num1'])
            m['num2'] = (fem.cleaned_data['num2'])
            f = (fem.cleaned_data['op'])
            v = m['num2']+f+m['num1']

            m['result'] = eval(v)
            print((m['result']))
            # return HttpResponseRedirect(reverse('app1:math'))
        else:
            return render(request, 'app1/Math.html', {
                'M_form': fem,
                'r': 0
            })
    return render(request, 'app1/Math.html', {
        'M_form': maths(),
        'r': m['result'],

    })


def table(request):
    data = members.objects.all()
    # for i in data:
    #     print(i['name'])
    print(f'{data} data is')
    data2 = {
        'Ttable': data
    }
    return render(request, 'app1/table.html', data2)


class newRegistration(forms.Form):
    name = forms.CharField(label='Name  :', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    lastName = forms.CharField(label='Last Name :', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    FatherName = forms.CharField(label='Father"s Name :', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    Address = forms.CharField(label='Address :', widget=forms.TextInput(
        attrs={'class': 'form-control'}))


def reg(request):

    if request.method == "POST":
        fem = newRegistration(request.POST)
        if fem.is_valid():
            Name = (fem.cleaned_data['name'])
            LastName = (fem.cleaned_data['lastName'])
            FatherName = (fem.cleaned_data['FatherName'])
            Address = (fem.cleaned_data['Address'])
            dt = members(name = Name, lastName = LastName, father = FatherName, address = Address)
            dt.save()
            
        else:
            return render(request, 'app1/reg.html', {
                'form': fem,
                
            })
    return render(request, 'app1/reg.html', {
        'form': newRegistration(),
         

    })

app1/templates/app1/Math.html
{% extends 'app1/base.html' %} {% block body %} {% include "app1/header.html" %}

<div class="container">
  <h1>This is Home page</h1>

  <form action="{% url 'app1:math' %}" method="post">
    {% csrf_token %} 
    {{M_form}}

    <input type="submit" />
      <h1>  {{r}}</h1>
    <input type ="text" value = "{{r}}">
  </form>

  <a href="{% url 'app1:contact' %}">Contact</a>
</div>
{% endblock body %}

app1/templates/app1/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/style.css' %}">
  </head>
  <body>
      
    {% block body %}{% endblock body %}
  </body>
</html>

 
     
 
     
 

app1/templates/app1/contact.html
{% extends 'app1/base.html' %}

{% block body %}
{% include "app1/header.html" %}
<div class="setting">
<h1> Contact</h1>
 <ul>
{% for v in task %}
<li>{{v}}</li>
{% endfor %}
</ul>
<a href="{% url 'app1:home' %}">Back</a>
</div>
{% endblock body %}

app1/templates/app1/header.html
<div class="navbar">
    <ul>
        <li><a href="{% url 'app1:home' %}">Home</a></li>
        <li><a href="{% url 'app1:math' %}">Math</a></li>
        <li><a href="{% url 'app1:table' %}">Table</a></li>
        <li><a href="{% url 'app1:contact' %}">contact</a></li>
        <li><a href="{% url 'app1:reg' %}">Registration</a></li>
    </ul>
</div>

app1/templates/app1/index.html
{% extends 'app1/base.html' %} {% block body %} {% include "app1/header.html" %}

<div class="container">
  <h1>This is Home page</h1>

  <form action="{% url 'app1:home' %}" method="post">
    {% csrf_token %} {{form}}

    <input type="submit" />
  </form>

  <a href="{% url 'app1:contact' %}">Contact</a>
</div>
{% endblock body %}

app1/templates/app1/reg.html
{% extends 'app1/base.html' %} {% block body %} {% include "app1/header.html" %}

<div class="container">
  <h1>This is Home page</h1>

  <form action="{% url 'app1:reg' %}" method="post">
    {% csrf_token %} {{form}}

    <input id  ="one" type="submit" />
  </form>

  <a href="{% url 'app1:contact' %}">Contact</a>
</div>
<script>
  var item = document.getElementById("one");
item.onclick = function() {
	document.getElementById('one').style.marginLeft = "50px";
  
}
</script>
{% endblock body %}

app1/templates/app1/table.html
{% extends 'app1/base.html' %} {% block body %} {% include "app1/header.html" %}

<div class="container">
  <h1>This is Table page</h1>
 <table class="table table-striped table-dark">
  <tr><th scope="col">ID</th>  <th scope="col">Name</th>  <th scope="col">Last Name</th>  <th scope="col">Father</th>  <th scope="col">Address</th></tr> 

 {% for h in Ttable  %}
 
 <tr>
  
  <th scope="row">{{h.id}}</th> <td>{{h.name}}</td>  <td>{{h.lastName}}</td>  <td>{{h.father}}</td>  <td>{{h.address}}</td>

</tr>
 
 {% endfor %}
 </table>
  <a href="{% url 'app1:math' %}">Math</a>
</div>
{% endblock body %}